---
- name: Add MongoDB public GPG Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: Add MongoDB 4 Repo
  apt_repository:
    repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse
    state: present
    filename: mongodb-org-4.0

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    force_apt_get: True

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    force_apt_get: True

- name: Install MongoDB packages
  apt:
    name: "{{ mongo_packages }}"
    force_apt_get: True

